### ISSUE TITLE
nodejs 14 not longer supported.

### ISSUE THREAD

**Issue by Afjal12** [Uniswap/uniswapx-parameterization-api#274]
Here is the error during deployment to aws.

Please resolve it.

Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 520601cd-7e07-4e56-9e3b-c807834bf548)" (RequestToken: c026e6a4-6011-591a-3b44-9b301a58a20b, HandlerErrorCode: InvalidRequest)
2024-03-04 13:05:37 UTC+0530	QueryRedshiftDatabase3de5bea727da479686625efb56431b5f3DF81997	
CREATE_IN_PROGRESS

Thanks.

**Comment by ConjunctiveNormalForm** [comment]
If you search for `aws_lambda.Runtime` you'll see that all lambdas are configure with node 18 as runtime.
